### ISSUE TITLE
Unable to Establish a Connection with XMPP Server

### ISSUE THREAD

**Issue by sureshrapur** [evothings/xmpp-hybrid-app-examples#1]
Hi,
I tried running your sample. I am always getting the connection status as "Connecting". No matter what I do, I am unable to get the successful connection with XMPP server. Can you let me know if I am missing any thing.

Below are my connection details in the code

```
        var connection = new Strophe.Connection('tcp://104.215.199.141') 
        connection.connect('testuser3@localhost', 'pwd', onConnectionCallback);
```

When I use 'ws://...' uri in the connection, I get status 1,2 and 6 back from the server. For TCP, I just get the status as 1.

-Suresh

**Comment by sureshrapur** [comment]
Below are my connection details in the code

            var connection = new Strophe.Connection('tcp://104.215.199.141') 
            connection.connect('testuser3@localhost', 'pwd', onConnectionCallback);

**Comment by fredrikeldh** [comment]
Did you use Evothings Client? If not, please try it. See the [readme](https://github.com/evothings/xmpp-hybrid-app-examples/blob/master/README.md).

**Comment by sureshrapur** [comment]
I am creating Cordova app using the Cordova command-line tools. I read the instructions.

**Comment by fredrikeldh** [comment]
Then I don't know what's wrong. Perhaps you can try looking at the native log system to get more information. `adb logcat` for Android, xcode for iOS.

**Comment by sureshrapur** [comment]
Thanks for the quick responses. I really appreciate it :-)

**Comment by sureshrapur** [comment]
Working fine with Evothings Client.
