### ISSUE TITLE
Is TCP communication secure or not

### ISSUE THREAD

**Issue by sureshrapur** [evothings/xmpp-hybrid-app-examples#2]
Hi,

By using chrome sockets, can the communication between hybrid client and the XMPP server be secured at the transportation level similar to 'https' or 'wss' ?

Thanks,
Suresh

**Comment by fredrikeldh** [comment]
Yes. If the server sends a < starttls > tag, then TLS is used.

**Comment by sureshrapur** [comment]
Can you please let me know what tag server should send ?

-Suresh

**Comment by fredrikeldh** [comment]
Sorry, github decided to hide the text in <>.
